### ISSUE TITLE
Ask for data

### ISSUE THREAD

**Issue by lixingguang** [blab/roka#5]
@alliblk Could you please send me the following four files to me, please, thanks.
Roka_PROT_192seq_08012016.fasta
MRCA_PROT_fasta_23032016.fasta
Roka_RT_192seq_08012016.fasta
MRCA_RT_fasta_23032016.fasta
Roka_Env_30112015.fasta
MRCA_Env_fasta_23032016.fasta

**Comment by trvrb** [comment]
All fastas are within the `data/` directory: https://github.com/blab/roka/tree/master/data.
